### ISSUE TITLE
Cache key not consistent across multiple servers

### ISSUE THREAD

**Issue by martyciz** [Selleo/pattern#16]
`.hash` method has inconsistent results across different servers / ruby processes (see [link](https://stackoverflow.com/questions/6536885/consistent-stringhash-based-only-on-the-strings-content)).

I suggest replacing it with consistent method : Digest::SHA1.hexdigest.
Here's my pull request: #15

**Comment by bartoszmaka** [comment]
Done in https://github.com/Selleo/pattern/pull/26
