### ISSUE TITLE
Rails cache fetch is called even when cache expiry period is blank

### ISSUE THREAD

**Issue by martyciz** [Selleo/pattern#17]
Expected behaviour:
Not setting `cache_expiry_period` to anything should prevent any calls to cache store.

Actual behaviour:
When using Redis `:redis_cache_store`, it still makes SET requests to cache store and stores value for each calculation call.

Fix: Prevent calling `Rails.cache.fetch` when `cache_expiry_period` is blank to avoid this. Note that doing so makes setting `force: ` option useless, so it can be removed.

Pull request: #14

**Comment by bartoszmaka** [comment]
I've added a test scenario for the issue https://github.com/Selleo/pattern/pull/25
It will be merged soon

**Comment by bartoszmaka** [comment]
Done
