### ISSUE TITLE
Warning: Using the last argument as keyword parameters is deprecated

### ISSUE THREAD

**Issue by colem213** [Selleo/pattern#24]
Rails issue: rails/rails#38202

Another link from the rails issue explaining the deprecation.  
https://piechowski.io/post/last-arg-keyword-deprecated-ruby-2-7/

**Comment by idegard** [comment]
This is related to [handling argument delegation](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/)

I only use service pattern so I ended up [extracting the pattern](https://github.com/Selleo/pattern/blob/94cd46df28ba09a48b101e6757813b21727cb040/lib/patterns/service.rb#L5) fixing the delegation lines

```ruby
def self.call(*args, **kwargs, &block)
  new(*args, **kwargs, &block).tap do |service|
    service.instance_variable_set(
      "@result",
      service.call
    )
  end
end
```

**Comment by bartoszmaka** [comment]
Service argument delegation has been updated in this PR: https://github.com/Selleo/pattern/pull/27

**Comment by bartoszmaka** [comment]
I'm currently working on solution compatible with ruby < 2.7 as well in this PR: https://github.com/Selleo/pattern/pull/29

**Comment by bartoszmaka** [comment]
Merged and published
